services:
  php:
    image: php:8.3-fpm
    working_dir: /var/www
    volumes:
      - ./services/api:/var/www
      - ./docker/php-fpm/zz-pm.conf:/usr/local/etc/php-fpm.d/zz-pm.conf:ro
    environment:
      SCANNER_BASE_URL: http://scanner:3001

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./services/api:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  scanner:
    build: ./services/scanner-node
    ports:
      - "3001:3001"
